"""Scheduling helpers for periodic valve maintenance (anti-stick).

Pure, deterministic time math. Randomised jitter is generated by the caller and
passed in so these functions stay unit-testable. Adapted from Better
Thermostat's ``utils/valve_maintenance.py``.
"""

from __future__ import annotations

from datetime import datetime, timedelta

# Fraction of the interval used as the maximum random jitter, so multiple
# thermostats don't all run maintenance at the same instant.
JITTER_FRACTION = 0.07


def next_maintenance_time(
    now: datetime, interval_days: float, jitter_hours: float = 0.0
) -> datetime:
    """Return the next maintenance time: now + interval + jitter."""
    return now + timedelta(days=interval_days, hours=max(0.0, jitter_hours))


def initial_maintenance_time(
    now: datetime, interval_days: float, fraction: float = 0.5
) -> datetime:
    """Return the first maintenance time after startup.

    Schedules within ``fraction`` of the interval (default halfway) so a fresh
    install exercises the valve reasonably soon without firing immediately on
    every restart.
    """
    delay_days = max(0.0, min(1.0, fraction)) * interval_days
    # Always wait at least an hour after startup.
    return now + max(timedelta(hours=1), timedelta(days=delay_days))


def max_jitter_hours(interval_days: float) -> float:
    """Maximum jitter (hours) for the given interval."""
    return interval_days * 24.0 * JITTER_FRACTION
